### PR TITLE
Adjustment to how binaries are built from CMake, small README change

### PR DESCRIPTION
**Pull request by zwookie**
I added to the Find package files to (hopefully) work on Windows. I used the `${CMAKE_SOURCE_DIR}` variable and then it should look into the respective includes or lib that you have in your directory. I also fixed the issue with building the binaries on my end. I noticed that the way resources such as textures and models were being loaded would move three times up from the current directory. 

For instance: `unsigned char* image = SOIL_load_image("../../../resources/textures/container.jpg", &width, &height, 0, SOIL_LOAD_RGB);`
But when the binaries were being built they would only look up two times from the current directory:
`RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/${CHAPTER}"`

So I added the extra bin directory. Its kind of a cheap workaround but it fixed all the issues on that front. I tried to get the individual chapters to build (similar how the src directory is set up) but I couldn't figure it out. In other words, I was trying to do `${CMAKE_SOURCE_DIR}/bin/${CHAPTER_MAJOR}/${CHAPTER_MINOR}` but couldn't figure it out. 

And a small change to the README for Linux building to make it more comprehensive.

### CODE REVIEW

**Comment by zwookie** [comment]
We can also set it up to work from the directory that the user specifies when the create their build directory. So instead of forcing the executables to a specific directory we can let the IDE put them where it naturally would and link the resources / shaders that way. That's kind of what I had with the recursive CMake system but it didn't work with VS as you noted. I have a Windows 7 machine and I'll test the CMake using VS as an IDE to see if I can get a better idea of how to get it work on both systems.

**Comment by JoeyDeVries** [comment]
Alright, let me know what you find :) 
I've been a bit sceptical with the recursive approach since that meant that I'd have to create a specific CMakeLists.txt for each specific project so that's why I'd prefer the current approach. But if you can find something interesting with the textures that'd be nice :D

**Comment by zwookie** [comment]
I think I may have found a fix that should work for both Linux and Windows users. I've been putting If(WIN32) / Endif() around the lines where you set up for Visual Studio, and then in the elseif I am putting what seems to work for Linux. I haven't tested it on my Windows machine yet but it did solve the issues I was having with CodeBlocks (except for resources). Now it no longer makes the bin/ directory but instead uses the build directory that I specify using CMake. And then on Windows it (should) still create the bin/ directory as you originally intended (but I haven't tested it and I have to head off to work now ...). However, the issue with resources still remains because its still searching 3 directories up from the current directory where the binaries are. Modifying the source directory could work, but I think it would be easier and less buggy to figure out how to get it to work in CMake (there's no reason why it shouldn't). So I would say don't worry about modifying your sources for now and I'll see if I can figure out how to get CMake to specify the Chapter Major / Chapter Minor directories when it builds the binaries.

**Comment by JoeyDeVries** [comment]
Cool, I've been a bit busy so couldn't check the windows versions today and probably too busy tommorow as well, sorry :'(   
This is where it builds when I build with visual studio on Debug mode http://prntscr.com/6orx1t   Here you can also see why I go up 3 directories ;)   
I'll have some time this weekend to test and tweak where necessery

**Comment by zwookie** [comment]
I tested the build system on Windows, and as expected it doesn't find the libraries correctly, however, I was able to point it to the right location (I was using cmake-gui) and it generated the Visual Studio solutions which is nice. Unfortunately, I found out that my license for Visual Studio had expired so I wasn't able to do anything.

**Comment by JoeyDeVries** [comment]
If it doesn't find the libraries correctly, isn't it easier to just use this statement: link_directories(${CMAKE_SOURCE_DIR}/lib)  and set them with 
if(WIN32)
  set(LIBS glfw3 opengl32 glew32s SOIL assimp) 
as before? This worked for me on windows just fine with regards to libraries. In that case it probably makes more sense to keep it as that and only when using Linux use the more advanced find* scripts.

I also found this: http://stackoverflow.com/questions/7747857/in-cmake-how-do-i-work-around-the-debug-and-release-directories-visual-studio-2  that discusses the output directory. I'll try that one this weekend which should ensure that each project builds to the same output directory. That way we'd have no issues with the resources since the output directories are the same for each project. If that works I think the CMakeFile is as good as done :)

**Comment by zwookie** [comment]
I reactivated my Visual Studio community license and tested the build and every project works running from the IDE except 3.1 model loader (it can't find the dll). Obviously not a huge deal since the user can just copy paste the dll from the dlls folder into there but I figure I should mention it. I also made a small change to the Find*.cmake files and now they all automatically find the required libs and includes for me.

**Comment by JoeyDeVries** [comment]
Yeah I did the .DLL on purpose since I don't want to copy the DLLs to each project (they're huge :p) so the users have to manually copy them to proper directories, but that's an acceptable tradeoff :)

And amazing work! I'm going to merge the request somewhere today, test it on my systems and I think that that's it :D Thank you so much for being the bridge between myself and the Linux requirements.

I want to add your name to the code repository page on learnopengl.com to thank you, is that oké? and what name would you like me to use? (inner_product, zach, zwookie?)

**Comment by zwookie** [comment]
zwookie is fine :bowtie:

**Pull request merged**
