### PR TITLE
Fix more errors on OSX

### PR DESCRIPTION
**Pull request by 64**
I just went through all the executables on OSX (turns out bash scripting is very helpful in that regard).

All of them "work", as in they run and seem to produce meaningful output, but I can't say for sure that the behaviour is exactly the same as how it is on Windows. For chapters 4 through 7 I needed to add the commented out line in each executable to get anything to work (this is the bulk of the diff).

A bit of a nitpick here, but your comment says "uncomment this statement to fix compilation on OS X", when in fact the *compilation* is fine, but running the program will cause `glfwCreateWindow` to return `nullptr` and exit. It's not really important but it may be a source of confusion to some users.

In the chapter 7 debugging example, I also renamed the fragment shader from `debugging.frag` to `debugging.fs` to ensure that cmake copied the shaders correctly. (The output is supposed to be just a black screen for that one, isn't it?)

Another issue I noticed is that in some of the chapter 5 programs (specifically, 3.1.1 -  3.2.2) the viewport occupied only the bottom left quarter of the screen. I believe this is due to the `glViewport` call interacting with the retina display, but I'm not entirely sure. Perhaps I'll investigate this another time.

My editor seems to go wild inserting newlines at the end of files (which makes some compilers happy). If that's annoying I could probably undo those changes. 

If there's anything else you want me to investigate on OSX then I'd be more than happy to do so.

### CODE REVIEW

**Comment by JoeyDeVries** [comment]
I agree, the statement isn't really correct. I'll have to do something of a find-and-replace-all to turn it into something like 'uncomment this statement to fix execution on OS X' or '... to properly initialize a modern GL context on OS X'.

The bottom-left quarter of the screen is because of retina displays' usual doubled resolution (so you're right). As we set `glViewport` based on the initial framebuffer dimensions (800x600), it doesn't take the doubled retina resolution into account, simply rendering everything at 1 quarter of a scale.

I thought I'd have fixed this by relying on GLFW's framebuffer_size callback which I hoped would automatically take the Retina's resolution into account, but appareantly it didn't :(. In that case I'd probably have to work in a `glfwGetFramebufferSize` call somewhere, which gives you the correct resolution on both normal and retina displays: http://www.glfw.org/docs/latest/group__window.html#ga0e2637a4161afb283f5300c7f94785c9.

**Comment by 64** [comment]
Yeah, I tried doing that before and that seemed to make it full screen. I think the callback you mentioned only gets called when you resize the window (and considering the mouse is locked, you can't resize anyway) - but you're also calling `glViewport` in the middle of the render loop so it immediately gets overridden.

**Comment by JoeyDeVries** [comment]
Yeah, I was assuming the callback also gets called at startup (which seems a reasonable thing to do for any windowing library to make issues like these easier to solve), but appareantly that assumption was wrong. I don't believe I'm calling `glViewport` in the middle of the render loops (that would indeed negate any effort); I took a look at several random examples and none of them call `glViewport` in the render loop. The only ones I can think of are samples like 'shadow mapping' where the shadow render is rendered w/ custom viewport settings.

**Comment by 64** [comment]
https://github.com/JoeyDeVries/LearnOpenGL/blob/master/src/5.advanced_lighting/3.1.1.shadow_mapping_depth/shadow_mapping_depth.cpp#L188

Yeah, those examples were the ones that I was talking about in my original post. All of the other examples occupy the whole screen.

**Comment by JoeyDeVries** [comment]
Ahh yes, I should add a call to `glfwGetFramebufferSize` there as well then.

**Pull request merged**
