### PR TITLE
fix compiler/linker warning messages

### PR DESCRIPTION
**Pull request by pattakosn**
There were a lot of warning messages generated when I built your examples which is confusing for me and anyway I thought that such a great project deserves to build cleanly!

Most commits are rather small and I think well commented to understand and decide if you like them or not.
The only "big" one is the one fixing narrowing conversion. I did not try to change the code to actually use doubles (which might have been the Good Thing to do), I mostly casted what already implicit narrowing conversions.

### CODE REVIEW

**Comment by JoeyDeVries** [comment]
Great changes. I agree with all of your commits, except the fix for narrowing conversions. At one point I moved away from all of GL's typedefs (`GLFloat`, `GLSizei`) as I just felt it added bloat to an already confusing subject where there's alternatives in the C++ standards anyways. If you can change these to their default C++ type e.g. `float`,  `size_t` then I can merge it in. Also I personally prefer explicit typing unless I'm working with crazy type names (like in iterators) so I'd rather not have `auto` in there for the cases you've used it.

**Comment by pattakosn** [comment]
I also do not like wrappers to C/C++ basic types but then there is the problem of different type sizes. I would expect that in an OpenGL project it is better to stick to OpenGL "types".

Regarding auto, I think it was better as it was but hey, your house your rules :)

**Comment by JoeyDeVries** [comment]
I personally think the OpenGL types are a bit too much bloat. I'd rather stick to the fixed-width standard types of C++. Currently there's no fixed-width types, but in chapters regarding data and packing I'll use these and mention the appropriate headers. For now I'd prefer to stick to the standard types over the GL types :)

**Comment by JoeyDeVries** [comment]
If you'd rather not revert these changes I get that as well, but would you then make a PR without that specific commit? The other changes are fine for a merge on my end

**Comment by pattakosn** [comment]
I have already updated the MR with an additional commit which undoes the usage of auto/GLtypes. If you can not see it then I am doing sth wrong.

**Comment by pattakosn** [comment]
As much as I ma interested in discussing your opinion on auto/GLtypes, when it comes to this MR, this is your project and your opinion is the Correct One :)

**Comment by JoeyDeVries** [comment]
Hehe yeah, I completely missed your commit in between the messages, it worked correctly :) merging it. Thanks for the help!

**Comment by pattakosn** [comment]
Thank you for your guide, it is amazing.

**Pull request merged**
