### PR TITLE
Support for out-of-source builds.

### PR DESCRIPTION
**Pull request by ibbles**
Uses an environment variable to tell the program where to find resource files.
Shader sources are still search for in the current working directory.

From the readme:

> Note that using CodeBlocks or an IDE may have issues
> running the programs due to problems finding the shader
> and resource files.

This turned out to be a real problem with CLion, which places everything CMake related and all compiled binaries in its own hidden folders. To work around this I made it possible to set an environment variable (LOGL_ROOT_PATH for now). If that is set, then resource files are search there. If not, then the same ../../../ relative path as before is used.

### CODE REVIEW

**Comment by JoeyDeVries** [comment]
I appreciate the work, but I'm not sure I want to merge the pull request.

This setup requires every user to configure an environment variable, which is an extra step necessary that isn't immediately obvious to most users when compiling the project, which doesn't by itself feel as the perfect solution. The best solution would be if it was somehow possible to update the CMakeFile such that all binaries end up in the same folder (instead of being compiler/IDE-dependent), but I'm not sure whether something like that is possible.

I hope you understand, this does indeed solve the issue and it's a nice extra tool, but people would still have to manually set up an environment variable even though the system does already work in most IDEs.

I'll leave the pull request open to see if other user's would like to place some comments and browse through the code.

**Comment by JoeyDeVries** [comment]
I'll also leave it open so readers can actually pull from your branche if they'd indeed prefer this solution :)

**Comment by ibbles** [comment]
> This setup requires every user to configure an environment variable...

No. Any user who does not set the environment variable gets the old behaviour, i.e. ../../../\<path\> is searched. So any current installation would still work after this change.

> The best solution would be if it was somehow possible to update the CMakeFile such that all binaries end up in the same folder, but I'm not sure whether something like that is possible.

I agree, and I don't know of any way either. Other than [install](http://www.cmake.org/cmake/help/v3.0/command/install.html) and setting the install path to somewhere in the source tree, which also requires a separate step by the user to do the actual installing. Unless that can be made to happen automatically.

Another alternative is to do something similar to the [add_custom_command](http://www.cmake.org/cmake/help/v3.0/command/add_custom_command.html) that copies shaders, but copy the entire resource folder. This is wasteful (in both time and space) if the resource folder is large.

**Comment by ibbles** [comment]
A separate note, I had to change a `std::sqrtf` to `std::sqrt` because there is [no sqrtf](http://en.cppreference.com/w/cpp/numeric/math) in the standard library. That change was accidentally included in this commit.

**Comment by JoeyDeVries** [comment]
> No. Any user who does not set the environment variable gets the old behaviour, i.e. ../../../<path> is searched. So any current installation would still work after this change.
Oops then I read the code too quickly, my bad. In that case I'll merge the results with the repository as it then wouldn't (potentially) trouble unaware users. 

I'll do a few extra checks later this week to see if everything still works solid as it probably will. Thanks for the contribution! Would you also be so kind to add a small statement in the README file regarding the environment variable?

Thanks! :D

**Comment by ibbles** [comment]
Small statement added to README.

**Pull request merged**
