### PR TITLE
Destroy FT_Face object only if we managed to create it.

### PR DESCRIPTION
**Pull request by mahiuchun**

### CODE REVIEW

**Comment by rbarkmore** [comment]
Good catch, that makes perfect sense.

**Comment by JoeyDeVries** [comment]
While technically correct, I don't feel it adds enough to break the tutorial flow (as I'd have to discuss cleaning up resources twice in tutorial text as it's fragmented in 2 code samples). Reason why I don't feel it adds enough is that if the face fails to load the demo won't run properly anyways (and we get an error message). For that reason I'm leaving this one open to keep text-code + source code consistent. Hope you understand!

**Comment by mahiuchun** [comment]
I see. In this case would you mind add `exit(EXIT_FAILURE)` when errors are detected?
On my (Linux) system the font fails to load for some reason then it becomes a segfault. Still trying to figure out why.

**Comment by JoeyDeVries** [comment]
Not at all, I've added several `return -1` (keeping it consistent with other error return paths). Should at least prevent the segfaults then.

**Comment by mahiuchun** [comment]
Thanks!

**Pull request closed without merging**
