### PR TITLE
model_animation.h flaws and missing Tangents!

### PR DESCRIPTION
**Pull request by JG-Adams**
Love your tutorial! Been programming for years prior.

I found a bunch of problem here I could fix:
* namespace std; should not be in header file. So I put in std:: in everything that need it. (at least in here.)
* #include <stb_image.h> causes compiler error. It's already established in Main.cpp.
* Use const std::string&
* The gamma formating in the TextureFromFile()

I also put in:
	vertex.Tangent = AssimpGLMHelpers::GetGLMVec(mesh->mTangents[i]);
	vertex.Bitangent = AssimpGLMHelpers::GetGLMVec(mesh->mBitangents[i]);

This need to be put there. I was confounded by the lack of normal mapping effects for hours!

### CODE REVIEW

**Comment by MMJoeyDeVries** [comment]
Everything looks great except the removal of stb_image.h, it should have include guards so not sure why it's complaining that it's already included, that shouldn't happen. And I prefer to keep it in as model_animation.h **is** using stb_image. Something else may be going on with your compile erorr?

**Comment by JoeyDeVries** [comment]
Everything looks great except the removal of stb_image.h, it should have include guards so not sure why it's complaining that it's already included, that shouldn't happen. And I prefer to keep it in as model_animation.h is using stb_image. Something else may be going on with your compile erorr?

**Comment by JG-Adams** [comment]
Howdy! Yeah, I'm not sure why that happens. But if you think it should stay there then that's fine with me! :)
It doesn't appear to have header guard?? I must have a wrong file or something. I'll fix it. :)
I have two version here, one with and another without. I don't know how to remove the removal part. I'm new to GitHub.

Also, I had issue Filesystem things. If I understand right, using cmake should apply the root directory?
It wasn't working right for me and I couldn't make sense of it. So I simply removed it and manually acquired the path to the models. At first for a while, I didn't know the codes was here. I thought it was a C++ feature!
This actually had me real confused as there is no explanation for it in the tutorial. Great tutorial though! Awesome stuff! :)

**Comment by JG-Adams** [comment]
I didn't get notification for this for some reason. O_o

**Comment by JG-Adams** [comment]
Here we go! That should put it back I hope?

**Comment by JG-Adams** [comment]
Ummmm... This is strange. I check the stb_image.h file and it does in fact have a header guard to it.
I don't understand why this happens.

However, I do find that I had to put in #define STB_IMAGE_IMPLEMENTATION prior to it.
This is done once. But I'm guessing this mess with how it's includes them? But it won't work without it.
How did it happens to work on your machine? I look at the texture example and it clearly doesn't have it.
Very puzzling.....   ~  _
                            O_o

**Comment by JG-Adams** [comment]
Ugh. GitHub is great but confusing.

**Comment by JoeyDeVries** [comment]
Eheh, I can't merge too many changes without doing extensive tests and whether I agree with changes from an educational perspective as well; since they're all part of a tutorial and text. From a quick glance this looks like positive changes, but things that distract from the core of the tutorial. In which case it's fine leaving this open for people to take inspiration from, but not sure I want to merge this.

However, this is from a guest article so I'll leave it to @NonLinearGuy if you want these changes in?

**Comment by JG-Adams** [comment]
> Eheh, I can't merge too many changes without doing extensive tests and whether I agree with changes from an educational perspective as well; since they're all part of a tutorial and text. From a quick glance this looks like positive changes, but things that distract from the core of the tutorial. In which case it's fine leaving this open for people to take inspiration from, but not sure I want to merge this.
> 
> However, this is from a guest article so I'll leave it to @NonLinearGuy if you want these changes in?

Yeah, sorry I might have overdid it. lol
Sound reasonable leaving it up to the host. If that could be possible.
On the educational perspective, I do think that perhap maintaining certain consistency with gammarizing, and having tangent with all the other tutorial you have might be good. Then again, it could be better for reader to recognize that and come with their own solution. But the missing tangent things actually had me confused.

I don't mind if it doesn't get merged in. But if it help in anyway I'll be glad to have made a contribution :)

**Pull request closed without merging**
