### PR TITLE
Cleanup and optimize PBR shader

### PR DESCRIPTION
**Pull request by stfx**
Needs to be done for other versions too

### CODE REVIEW

**Comment by JoeyDeVries** [comment]
I agree with your changes. However, a large part of how I write code for LearnOpenGL is quite (unnecessary) explicit without much care for smaller optimizations to keep things just a bit easier to read when introducing a topic so I'd prefer to keep it as they are.

**Comment by stfx** [comment]
I understand. So how about at least taking the NdotL and NdotV cache changes as that would make it easier for me to understand in the context of a tutorial too?

**Comment by JoeyDeVries** [comment]
NdotL and NdotV changes are fine, I've written them down for a future revision (for changes this small I won't change them right away as it takes a lot of time to keep all the PBR tutorials consistent on every change).

**Comment by stfx** [comment]
Since you merged related fixes and probably plan to update the shader I could offer to redo this PR for just the NdotL and NdotV cache changes as discussed above if you are interested

**Comment by JoeyDeVries** [comment]
Sure, thank you! I do have to edit the changes in the tutorial text before merging so it'll probably be 1-2 days after the PR that I'll merge the changes.

**Comment by stfx** [comment]
Resubmitted in #94

**Pull request closed without merging**
